### ISSUE TITLE
ReSCoSS with multiple input SMILES

### ISSUE THREAD

**Issue by CMargreitter** [MolecularAI/Icolos#3]
When running the ReSCoSS workflow with more than input SMILES (all of which work individually), the COSMO step fails with:

_In order to write out COSMO files, the content needs to be annotated as extra data in the conformers. Have you executed Turbomole before?_

Traceback (most recent call last):
  File "/projects/cc/mai/miniconda3/envs/icolosprod/bin/icolos", line 33, in <module>
    sys.exit(load_entry_point('icolos', 'console_scripts', 'icolos')())
  File "/projects/cc/mai/Icolos/src/icolos/scripts/executor.py", line 98, in main
    workflow.execute()
  File "/projects/cc/mai/Icolos/src/icolos/core/composite_agents/workflow.py", line 74, in execute
    step.execute()
  File "/projects/cc/mai/Icolos/src/icolos/core/workflow_steps/calculation/cosmo.py", line 272, in execute
    ) = self._prepare_tmp_input_directories(enumeration=inp_enum)
  File "/projects/cc/mai/Icolos/src/icolos/core/workflow_steps/calculation/cosmo.py", line 72, in _prepare_tmp_input_directories
    raise ValueError("Could not find COSMO data to write out - abort.")
ValueError: Could not find COSMO data to write out - abort.

**Comment by jharrymoore** [comment]
Fixed, bug in the turbomole parser, would always attach to the first compound.
